#!/usr/bin/bash

cd "${0%/*}"

echo 'Checking for updates in repo.'
git pull

echo '(Re-)building typescript-project.'
npx ng build --configuration=production

echo 'Deploying website...'
if [ -e ~/html/index.html ]; then
	echo 'Previous version found. Removing.'
	rm ~/html/*
fi

echo 'Copying new files.'
cp dist/stock-analysis/* ~/html/
echo 'Done.'
